#print('Programación explorador') #Imprimir

#solicitar un número al usuario

#numero=int(input("Por favor ingresa el número"))

#print(f"Has ingresado el número: {numero}")

#Tipos de datos en python

#Números enteros

edad=30

print(f"Edad = {edad}, tipo: {type (edad)}")

#Números flotantes
precio=23.5 

print(f"precio = {precio}, tipo: {type (precio)}")

#cadena de texto o script
nombre= "María"

print(f"nombre = {nombre}, tipo: {type (nombre)}")

# Números Booleanos

esmayor=True

print(f"Booleano = {esmayor}, tipo: {type(esmayor)}")

a=5
b=9
resultado=a+b
print(resultado)
